#Database Configuration
spring:
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: "jdbc:mysql://localhost:3306/fotman?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: "root"
    password: "root"
    platform: "mysql"
    initialization-mode: "always"
